[package]
name = "gemini"
authors = ["RedPenguin"]
edition = "2021"
version = "0.1.0"
description = "A monospaced ASCII rendering engine"
readme = "README.md"
license = "MIT"
keywords = ["gemini", "gamedev", "ascii", "game-engine", "rendering-engine"]
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1"