[package]
name = "gemini-engine"
authors = ["RedPenguin"]
edition = "2021"
version = "0.2.0"
description = "A monospaced ASCII rendering engine"
documentation = "https://docs.rs/gemini-engine"
readme = "README.md"
homepage = "https://github.com/redpenguinyt/gemini-rust"
repository = "https://github.com/redpenguinyt/gemini-rust"
license = "MIT"
keywords = ["gemini", "gamedev", "ascii", "game-engine", "rendering-engine"]
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1"